INSERT INTO RegisteredUser VALUES
(newid(), 'Dummy42', 'dummy', 'User', 'n/a', 'n/a', getdate(), getdate());

INSERT INTO BoardGame VALUES
(newid(), 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed porttitor odio. Donec pharetra mollis urna sed consequat. Integer in fringilla tellus, at rhoncus magna. Sed interdum rutrum nibh, ut viverra dolor tristique nec. Morbi risus nibh, blandit quis urna non, pellentesque vestibulum dolor. Donec dictum tristique bibendum. Sed vulputate, est a ultrices fringilla, urna nisl fermentum lectus, ac sagittis lorem enim nec dolor. Nulla a pulvinar eros. Phasellus ac lacus pulvinar quam tempor scelerisque consectetur quis risus. Nullam nulla ante, scelerisque scelerisque elit nec, pellentesque tristique nibh. Curabitur viverra orci ut arcu feugiat, et commodo metus pharetra. Vivamus ornare laoreet ligula ac aliquam. Sed nec elementum purus, rutrum pulvinar dolor. Nullam condimentum ultricies urna in malesuada. In volutpat fringilla tristique. ',
'SYSADMIN', 'n/a', getdate(), getdate());

INSERT INTO Review VALUES
(newid(), 'Ipsum Lorem', 'Vestibulum ligula urna, pharetra ac dapibus sed, posuere id tortor. Ut placerat lectus erat, sit amet feugiat massa ornare non. Etiam lorem tortor, dapibus at maximus vitae, lobortis in dui. Aliquam at mauris nec velit egestas dapibus ut blandit ipsum. Nunc ut lorem turpis. Etiam suscipit sem sit amet tempus luctus. Sed sit amet ullamcorper mauris, sagittis imperdiet orci. Vivamus viverra tempor risus ut pellentesque. Integer at erat lectus. Morbi vehicula lacinia leo. Donec vestibulum sollicitudin tellus, et luctus nisl bibendum non. ',
'5',(SELECT "Id" FROM "BoardGame" WHERE Title like 'Lorem Ipsum'), 'SYSADMIN', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'SYSADMIN'));

--------------------------------

INSERT INTO RegisteredUser VALUES (newid(), 'AliceW', 'Al!c3Pass', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'BobDylan', 'B0b$Song', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'CathyTech', 'C@thy1234', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'Dave_Gamer', 'Dav3G@m3', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'EvaArt', 'Ev@A#rtist', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'FrankCook', 'Fr@nkChef!', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'GraceHacker', 'Gr@c3C0de', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'HarryBuilder', 'H@rryBld', 'User', 'n/a', 'n/a', getdate(), getdate());
INSERT INTO RegisteredUser VALUES (newid(), 'IvyGardener', '1vyGr33n', 'User', 'n/a', 'n/a', getdate(), getdate());

----------------------------------

INSERT INTO BoardGame VALUES (newid(), 'Galactic Explorers', 'Explore the galaxies and claim uncharted planets. A thrilling space adventure for those who dare to venture beyond.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Mystery Mansion', 'Investigate haunting mysteries in a cursed mansion. Use wit and bravery to uncover the truth.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Ocean''s Depths', 'Dive into the ocean’s depths to discover hidden treasures and mystical creatures. A game of exploration and risk.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Kingdom Conquest', 'Build, expand, and defend your kingdom in this strategic game of medieval warfare and diplomacy.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Wild West Adventure', 'Become a cowboy or an outlaw in the Wild West. Who will rule the desert lands?', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Enchanted Forest', 'Navigate a magical forest filled with fantastical creatures and spells. A family-friendly fairy tale journey.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Pirate''s Plunder', 'Set sail on the high seas as a pirate captain. Seek treasure, battle enemies, and avoid the navy.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Robot Rebellion', 'The robots have revolted! Work together to quash the rebellion or join the robots in their uprising.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Dino Park Adventure', 'Create and manage your own dinosaur park. Keep the dinosaurs happy and the visitors safe!', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Space Station Survival', 'Stranded on a space station with limited resources. Work together to survive or sabotage others for your gain.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Vampire''s Curse', 'Survive the night in a town cursed by vampires. Find the hidden vampires or join their ranks.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Time Travelers', 'Travel through different eras and shape history in this game of intrigue and temporal manipulation.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Zombie Apocalypse', 'The dead have risen! Survive the zombie apocalypse with your wits, weapons, and teamwork.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Fairy Tale Showdown', 'Battle as iconic fairy tale characters in this whimsical card game of strategy and surprise.', 'SYSADMIN', 'n/a', getdate(), getdate());
INSERT INTO BoardGame VALUES (newid(), 'Cyberpunk City', 'In a dystopian future, hackers and corporations clash in a game of influence, technology, and power.', 'SYSADMIN', 'n/a', getdate(), getdate());

-----------------------------

INSERT INTO Review VALUES (newid(), 'Lorem Ipsum', 'A delightful game of words and wit. The strategic thinking required is both challenging and engaging.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Lorem Ipsum'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Catan', 'A classic game of strategy and trading. There''s nothing quite like the satisfaction of building the longest road!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A family favorite that never gets old. But watch out for those Draw Four cards!', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'Fast-paced and fun, this game tests your reflexes and matching skills like no other.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Dixit', 'A beautifully designed game that encourages creativity and storytelling. A joy to play with friends and family.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dixit'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'A classic word game that can be both fun and frustrating. Bring your best vocabulary!', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Ubongo', 'A puzzling game with a unique approach. It''s engaging but can become repetitive over time.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ubongo'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Codenames', 'A game of deduction and association that will have you second-guessing every clue.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Codenames'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Pandemic', 'Cooperation is key in this thrilling game of global disease control. Every decision counts!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pandemic'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'Embark on an adventure through the cosmos. Exciting but the rules can be complex for newcomers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'Explore the deep sea and discover its secrets. A refreshing theme but the gameplay lacks depth.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'Saddle up for an exciting journey in the Wild West. A well-crafted game with great replay value.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A magical game that captivates the imagination. However, the luck-based elements may not appeal to everyone.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'Ahoy! A swashbuckling adventure awaits in this treasure-hunting game. The theme is engaging but the gameplay could use more variety.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A thrilling journey through a park filled with dinosaurs. The theme is exciting, but the game mechanics might be too simple for seasoned players.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'Dummy42', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dummy42'));

INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'A futuristic adventure with endless possibilities. The tension builds with every turn.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'An intense survival game that will keep you on the edge of your seat. Perfect for fans of thrillers.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'An epic battle for control that can become heated among friends. Strategic thinking is a must!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'A unique theme and interesting mechanics, but somewhat lacking in replay value.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Risk', 'A true classic, but not for the faint of heart. Prepare for a long and challenging battle.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Risk'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'An engaging treasure hunt, but can become repetitive after a few plays.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Mystery Mansion', 'A thrilling mystery-solving experience. Perfect for those who love puzzles and intrigue.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Mystery Mansion'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A gothic and atmospheric game that creates an immersive experience, but some might find it too dark.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'A stylish and engaging game with a cool theme, but might be too complex for casual gamers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A fun and accessible game for all ages, but experienced gamers might find it too simple.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A whimsical game that appeals to the imagination. Great for playing with kids.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A magical and enchanting experience that transports you to another world. Simply beautiful!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'An innovative concept with a time-travel twist, but the mechanics can be confusing at times.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'Embark on a space adventure with friends. Interesting but might not appeal to everyone.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A classic card game that is always a hit at parties. Simple and fun for everyone.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'AliceW', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'AliceW'));

INSERT INTO Review VALUES (newid(), 'Catan', 'A timeless strategy game that fosters negotiation and planning. A must-have for board game enthusiasts.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'A quick and fun matching game that tests your reflexes. Great for all ages!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'A thrilling ride through the wild west, but the rules might be too complicated for some players.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Codenames', 'A clever word game that will test your connections with friends. Hours of fun!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Codenames'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Pandemic', 'An engaging cooperative game with real tension. A bit too challenging for some, but an excellent choice for strategy lovers.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pandemic'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Dixit', 'An imaginative and beautifully illustrated game. Great for creative thinkers.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dixit'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Ubongo', 'A puzzle game that''s both fun and frustrating. Some may find it too challenging.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ubongo'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'A serene and beautiful game with an ocean theme. It''s relaxing but may lack excitement for some.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'A unique game with a sci-fi twist. Engaging but requires a lot of setup.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'A classic word game that never gets old. Educational and fun for word lovers.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'An adventurous game with a space theme, but might be too complex for newcomers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'An atmospheric game with a unique theme. Some may find the rules confusing.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A fresh take on the adventure genre, with exciting time travel mechanics.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A whimsical game that''s perfect for families. May lack depth for serious gamers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'An intense and immersive game set in a dystopian future. Not for the casual player, but thrilling for those up for the challenge.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'BobDylan', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'BobDylan'));

INSERT INTO Review VALUES (newid(), 'Uno', 'A simple yet engaging card game that brings endless fun to the table. Perfect for family gatherings.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'An epic battle for supremacy, filled with strategy and intrigue. A must-have for any serious board game collector.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Risk', 'A classic game of world domination that''s both thrilling and challenging. May be too complex for some.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Risk'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A playful adventure with dinosaurs. Great for kids, but adults may find it lacking in depth.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'An outer-space adventure that promises excitement but falls short in execution. A bit disappointing.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'Sail the high seas in this swashbuckling adventure. A treasure of fun for the whole family.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Mystery Mansion', 'A suspenseful game full of twists and turns. Engaging but may be too complex for younger players.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Mystery Mansion'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A whimsical game that takes you into the world of fairy tales. Delightful but may lack challenge for some.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'A thrilling survival game with a zombie theme. Can be repetitive and unbalanced at times.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'A fast-paced matching game that''s always a hit. Suitable for all ages.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'The ultimate word game that challenges your vocabulary. A classic that never gets old.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A unique concept that''s executed well. The time-traveling mechanics add an exciting twist to the gameplay.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A haunting game with a rich theme. Complex rules may deter some players.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'An engaging game set in space, but with unpolished mechanics. Needs improvement to truly shine.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A magical journey through an enchanted forest. Charming but could use more complexity.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'CathyTech', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'CathyTech'));

INSERT INTO Review VALUES (newid(), 'Catan', 'A masterpiece of strategy and resource management. A must-play for anyone serious about board games.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'An exciting journey into the Wild West. Some mechanics might feel outdated, but still an enjoyable experience.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Pandemic', 'A thrilling cooperative game that teaches teamwork. Some might find it too difficult, but the challenge is part of the fun.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pandemic'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'An innovative concept that lacks polish. Interesting but needs more depth to be truly great.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'A futuristic rebellion that falls flat in execution. Interesting theme but lacking in fun gameplay.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A haunting game that truly captures the vampire theme. A bit complex but highly rewarding.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A family-friendly adventure with dinosaurs. Fun for kids but may be too simple for adults.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'A stylish game with a cyberpunk theme. Engaging but could use more strategic depth.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A creative take on time-traveling. Some mechanics feel gimmicky, but overall a good play.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Dixit', 'A visually stunning game that stimulates the imagination. Accessible and enjoyable for everyone.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dixit'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'A deep-sea adventure that feels shallow in gameplay. Interesting concept but needs improvement.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'A timeless word game that remains a challenge. Always enjoyable and educational.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A delightful game for fairy tale lovers. Lacks complexity but makes up for it with charm.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Ubongo', 'A puzzling game that''s fun but can become repetitive. Good for a casual game night.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ubongo'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'A survival game with a twist. The zombie theme is well-executed, but some mechanics feel unbalanced.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'Dave_Gamer', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'Dave_Gamer'));

INSERT INTO Review VALUES (newid(), 'Catan', 'An artful blend of strategy and cunning. A visually captivating game that''s fun and engaging.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'A light and entertaining game. Visually appealing but lacks depth for serious gamers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Risk', 'A classic game of global domination. Time-consuming but always thrilling.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Risk'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'A fun-filled pirate adventure that can become repetitive. Great for younger players.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'A futuristic game with a stunning visual design. Gameplay could be more engaging.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Mystery Mansion', 'An intriguing mystery game that keeps you on the edge of your seat. Challenging and fun.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Mystery Mansion'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'A space adventure that lacks a bit of innovation. The visuals are appealing, but gameplay needs improvement.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A magical game that enchants players of all ages. Simple yet satisfying.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A colorful dinosaur-themed game that''s great for families. Lacks complexity for hardcore gamers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'A game of royalty and conquest. Strategy-heavy and visually rich. A must-play!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A classic card game that never gets old. Simple but still entertaining.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Codenames', 'A clever word-based game that requires thinking and teamwork. Always a hit at game night.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Codenames'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'An engaging Wild West theme but falls short in execution. A bit disappointing.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'A thrilling survival game with an exciting zombie theme. Could use a bit more balance.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A whimsical fairy tale game that charms players. A bit simplistic but lovely nonetheless.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'EvaArt', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'EvaArt'));

INSERT INTO Review VALUES (newid(), 'Ubongo', 'A puzzling adventure that stirs the mind. Easy to learn but offers a real challenge. Deliciously complex!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ubongo'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'A thrilling survival game set in space. It''s a feast for the eyes but could use more depth in strategy.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Dixit', 'A creative and artistic game. A tasty blend of imagination and strategy.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dixit'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A classic card game that''s a bit bland for my taste. Good for a quick play but lacks spice.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'A word-building game that serves a challenging mental exercise. Always a treat to play!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A journey through time that''s interesting but a bit overcooked. Needs more balance.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A dark and thrilling game that sinks its teeth into you. Immersive and flavorful.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'A royal feast of strategy and competition. Rich in detail and endlessly entertaining.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Pandemic', 'A strategic game that''s as intense as a simmering pot. Teamwork is key, and it''s always satisfying.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pandemic'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A whimsical journey through a magical forest. Sweet and light, but could use more complexity.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'An underwater adventure that''s refreshing but lacks some depth. More content would be a splash!', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A family-friendly dinosaur game that''s tasty for younger players but lacks meat for adults.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'An action-packed Wild West ride. Engaging, flavorful, and full of surprises. Yeehaw!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'A futuristic robot game that''s a bit robotic in design. Interesting but needs more soul.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'A cosmic journey that''s a feast for the eyes. Strategic, challenging, and flavorful. A star in my collection!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'FrankCook', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'FrankCook'));

INSERT INTO Review VALUES (newid(), 'Risk', 'A global domination game that challenges your strategic skills. Innovative and clever, a true challenge!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Risk'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'A fast-paced matching game that offers a light and fun experience. Could use more depth for hardcore gamers.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'A tech-driven dystopian game that truly resonates with my hacker heart. Deep, immersive, and exciting.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'A futuristic adventure that blends AI and human interaction. Interesting but could use more innovation.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'A thrilling survival game with a perfect blend of strategy and horror. The suspense never stops!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'A treasure hunting adventure that lacks real treasure. Boring and unimaginative, not worth the time.', '1', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Mystery Mansion', 'A mysterious and puzzling game that keeps you guessing. Intriguing but sometimes confusing.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Mystery Mansion'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A whimsical game that falls flat. Lacks innovation and complexity, leaving much to be desired.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A dark and thrilling game that engages the mind and senses. A true gem!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A classic that has lost its charm over time. Simple and repetitive, not suitable for serious gamers.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'A thrilling adventure in the Wild West that''s full of action and excitement. Truly engaging!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'A cosmic experience that is out of this world. Fresh, exciting, and full of surprises.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Catan', 'A resource management game that has stood the test of time. Brilliantly designed but can be slow-paced.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'An underwater game that fails to dive deep. Lacks complexity and real adventure.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'A royal game that demands strategic thinking. Challenging, exciting, and worthy of replay.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'GraceHacker', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'GraceHacker'));

INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'A swashbuckling adventure that''s full of excitement, though the build quality of the pieces could be better.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A classic card game that never gets old. The simplicity of the design is its strongest point.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Kingdom Conquest', 'A beautifully crafted game that shows attention to detail in every piece. Strategy meets artistry.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Kingdom Conquest'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'The thematic elements are well-constructed, but the overall game lacks a cohesive structure. It feels disjointed.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'A charming concept with poorly executed game mechanics. The aesthetics are nice, but the gameplay falls flat.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A futuristic concept that has been brilliantly realized. The design and construction of the game are top-notch.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'An underwater exploration game that could use more depth in its design. The concept is intriguing, but execution lacks polish.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'A cosmic adventure with intricate design and well-thought-out gameplay. Engaging and aesthetically pleasing.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Robot Rebellion', 'The mechanical theme is intriguing but lacks depth. The construction is solid but not groundbreaking.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Robot Rebellion'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Cyberpunk City', 'A tech-driven game that could benefit from more refined design. Interesting concept but needs more innovation.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Cyberpunk City'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'A well-constructed game that explores the cosmos. Engaging gameplay and thoughtful design.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A prehistoric adventure that falls short in design complexity. The theme is fun but execution lacks excitement.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'A thrilling Western experience with detailed design and immersive gameplay. Truly a standout!', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'A simple and fast-paced game that''s great for quick fun but lacks the structural complexity I look for.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));
INSERT INTO Review VALUES (newid(), 'Scrabble', 'A word-building classic that''s well-constructed and always engaging. A staple for any game night!', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Scrabble'), 'HarryBuilder', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'HarryBuilder'));

INSERT INTO Review VALUES (newid(), 'Catan', 'A game that grows on you over time. Strategic and well-crafted. A bit like tending to a garden of opportunities.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Catan'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Ocean''s Depths', 'An exploration game with depth and beauty. It''s like diving into an underwater garden, full of surprises.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Ocean''s Depths'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Enchanted Forest', 'A whimsical and magical game that lacks proper nourishment in its rules. The idea is enchanting but needs pruning.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Enchanted Forest'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Pirate''s Plunder', 'A plundering good time but with a barren design. Needs more cultivation to truly thrive.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Pirate''s Plunder'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Wild West Adventure', 'A wild ride that''s full of adventure. Much like exploring an untamed wilderness, thrilling but can be overwhelming.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Wild West Adventure'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Zombie Apocalypse', 'A game that seems dead on arrival. The concept is there, but it fails to blossom into a satisfying experience.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Zombie Apocalypse'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Time Travelers', 'A blossoming concept that takes you through time and space. Unique and well-designed like a timeless garden piece.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Time Travelers'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Space Station Survival', 'An outer space survival game that lacks organic growth. The idea is there, but it needs more care and attention.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Space Station Survival'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Uno', 'A simple and timeless game. Like a well-tended garden, it offers comfort and joy to those who play.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Uno'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Dobble', 'Quick and sprightly, this game offers fast-paced fun but doesn''t have the depth or complexity for a full harvest of enjoyment.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dobble'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Dino Park Adventure', 'A prehistoric garden of fun. The thematic elements are appealing, but the gameplay could use a bit more cultivation.', '3', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Dino Park Adventure'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Mystery Mansion', 'A game with hidden layers and twists like a mysterious garden maze. Engaging and thought-provoking.', '4', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Mystery Mansion'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Vampire''s Curse', 'A haunting experience that lacks life. It''s like a garden that needs more nurturing to truly thrive.', '2', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Vampire''s Curse'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Fairy Tale Showdown', 'Whimsical and delightful as a blooming garden in spring. A true fairy tale experience that enchants players of all ages.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Fairy Tale Showdown'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));
INSERT INTO Review VALUES (newid(), 'Galactic Explorers', 'An exploration game that blossoms with creativity and innovation. Like discovering a new species of plant in a cosmic garden.', '5', (SELECT "Id" FROM "BoardGame" WHERE Title like 'Galactic Explorers'), 'IvyGardener', 'n/a', getdate(), getdate(), (SELECT "Id" FROM "RegisteredUser" WHERE Username like 'IvyGardener'));


